/** Built-in chat emotes — available immediately, no admin upload required. */

export type BuiltinMedia = {
  id: string;
  kind: 'sticker' | 'gif';
  name: string;
  previewUrl: string;
  assetUrl: string;
  createdAt: string;
};

/** Twemoji PNG from codepoints (e.g. "1f525"). */
function twemoji(code: string): string {
  return `https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/${code}.png`;
}

/** Large reaction-style stickers (Twemoji). */
export const BUILTIN_STICKERS: BuiltinMedia[] = [
  ['fire', 'Fire', '1f525'],
  ['100', '100', '1f4af'],
  ['clap', 'Clap', '1f44f'],
  ['thumbs', 'Thumbs up', '1f44d'],
  ['heart', 'Heart', '2764'],
  ['star', 'Star', '2b50'],
  ['rocket', 'Rocket', '1f680'],
  ['trophy', 'Trophy', '1f3c6'],
  ['skull', 'Skull', '1f480'],
  ['ghost', 'Ghost', '1f47b'],
  ['robot', 'Robot', '1f916'],
  ['alien', 'Alien', '1f47d'],
  ['game', 'Controller', '1f3ae'],
  ['joystick', 'Joystick', '1f579'],
  ['target', 'Bullseye', '1f3af'],
  ['dice', 'Dice', '1f3b2'],
  ['party', 'Party', '1f389'],
  ['confetti', 'Confetti', '1f38a'],
  ['flex', 'Flex', '1f4aa'],
  ['eyes', 'Eyes', '1f440'],
  ['think', 'Thinking', '1f914'],
  ['cool', 'Cool', '1f60e'],
  ['cry', 'Cry', '1f622'],
  ['rage', 'Rage', '1f621'],
  ['zzz', 'Sleep', '1f4a4'],
  ['boom', 'Boom', '1f4a5'],
  ['sparkles', 'Sparkles', '2728'],
  ['rainbow', 'Rainbow', '1f308'],
  ['pizza', 'Pizza', '1f355'],
  ['coffee', 'Coffee', '2615'],
].map(([id, name, code]) => {
  const url = twemoji(code);
  return {
    id: `builtin-sticker-${id}`,
    kind: 'sticker' as const,
    name,
    previewUrl: url,
    assetUrl: url,
    createdAt: '2020-01-01T00:00:00.000Z',
  };
});

const CREATED = '2020-01-01T00:00:00.000Z';

/** 100 HD reaction GIFs — Cult of the Party Parrot catalog (no admin upload). */
export const BUILTIN_GIFS: BuiltinMedia[] = [
  {
    id: 'builtin-gif-hdrparrot',
    kind: 'gif',
    name: "HDR",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/hdrparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/hdrparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-opensourceparrot',
    kind: 'gif',
    name: "Open-source",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/opensourceparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/opensourceparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-middleparrot',
    kind: 'gif',
    name: "Middle",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/middleparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/middleparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-reverseparrot',
    kind: 'gif',
    name: "Reverse",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-aussieparrot',
    kind: 'gif',
    name: "Aussie",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussieparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussieparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-gothparrot',
    kind: 'gif',
    name: "Goth",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/gothparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/gothparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-boredparrot',
    kind: 'gif',
    name: "Bored",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/boredparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/boredparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-shuffleparrot',
    kind: 'gif',
    name: "Shuffle",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/shuffleparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/shuffleparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-congaparrot',
    kind: 'gif',
    name: "Conga Line",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/congaparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/congaparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-reversecongaparrot',
    kind: 'gif',
    name: "Reverse Conga Line",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/reversecongaparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/reversecongaparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-partyparrot',
    kind: 'gif',
    name: "Party",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/partyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/partyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sadparrot',
    kind: 'gif',
    name: "Sad",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sadparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sadparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-copparrot',
    kind: 'gif',
    name: "Cop",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/copparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/copparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-fastparrot',
    kind: 'gif',
    name: "Fast",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/fastparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/fastparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-ultrafastparrot',
    kind: 'gif',
    name: "Ultra Fast",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/ultrafastparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/ultrafastparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-slowparrot',
    kind: 'gif',
    name: "Slow",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/slowparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/slowparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-dadparrot',
    kind: 'gif',
    name: "Dad",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/dadparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/dadparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-dealwithitparrot',
    kind: 'gif',
    name: "Deal With It",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/dealwithitparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/dealwithitparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-dealwithitnowparrot',
    kind: 'gif',
    name: "Deal With It Now",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/dealwithitnowparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/dealwithitnowparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sassyparrot',
    kind: 'gif',
    name: "Sassy",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sassyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sassyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-confusedparrot',
    kind: 'gif',
    name: "Confused",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/confusedparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/confusedparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-aussiecongaparrot',
    kind: 'gif',
    name: "Aussie Conga Line",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussiecongaparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussiecongaparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-aussiereversecongaparrot',
    kind: 'gif',
    name: "Aussie Reverse Conga Line",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussiereversecongaparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/aussiereversecongaparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-congapartyparrot',
    kind: 'gif',
    name: "Conga Party",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/congapartyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/congapartyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-moonwalkingparrot',
    kind: 'gif',
    name: "Moonwalking",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/moonwalkingparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/moonwalkingparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-thumbsupparrot',
    kind: 'gif',
    name: "Thumbs Up",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/thumbsupparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/thumbsupparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-coffeeparrot',
    kind: 'gif',
    name: "Coffee",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/coffeeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/coffeeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-mustacheparrot',
    kind: 'gif',
    name: "Parrot with mustache",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/mustacheparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/mustacheparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-christmasparrot',
    kind: 'gif',
    name: "Christmas",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/christmasparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/christmasparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sleepingparrot',
    kind: 'gif',
    name: "Sleepy",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sleepingparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sleepingparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-beerparrot',
    kind: 'gif',
    name: "Happy Hour",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/beerparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/beerparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-gentlemanparrot',
    kind: 'gif',
    name: "Gentleman",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/gentlemanparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/gentlemanparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-twinsparrot',
    kind: 'gif',
    name: "Twins",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/twinsparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/twinsparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-stableparrot',
    kind: 'gif',
    name: "Stable",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/stableparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/stableparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-wendyparrot',
    kind: 'gif',
    name: "Wendy's",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/wendyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/wendyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-popcornparrot',
    kind: 'gif',
    name: "Popcorn",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/popcornparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/popcornparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-popcornparrotofdarkness',
    kind: 'gif',
    name: "Popcorn Parrot of Darkness",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/popcornparrotofdarkness.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/popcornparrotofdarkness.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-donutparrot',
    kind: 'gif',
    name: "Donut",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/donutparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/donutparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-evilparrot',
    kind: 'gif',
    name: "Evil",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/evilparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/evilparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-discoparrot',
    kind: 'gif',
    name: "Disco",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/discoparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/discoparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-scienceparrot',
    kind: 'gif',
    name: "Science",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/scienceparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/scienceparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-revolutionparrot',
    kind: 'gif',
    name: "Revolution",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/revolutionparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/revolutionparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-birthdaypartyparrot',
    kind: 'gif',
    name: "Birthday Party",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/birthdaypartyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/birthdaypartyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-jediparrot',
    kind: 'gif',
    name: "Jedi",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/jediparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/jediparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sithparrot',
    kind: 'gif',
    name: "Sith",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sithparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sithparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-angryparrot',
    kind: 'gif',
    name: "Angry",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/angryparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/angryparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-invisibleparrot',
    kind: 'gif',
    name: "Invisible",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/invisibleparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/invisibleparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sushiparrot',
    kind: 'gif',
    name: "Sushi",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sushiparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sushiparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-pumpkinparrot',
    kind: 'gif',
    name: "Pumpkin",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/pumpkinparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/pumpkinparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-angelparrot',
    kind: 'gif',
    name: "Angel",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/angelparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/angelparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-bluntparrot',
    kind: 'gif',
    name: "Blunt",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/bluntparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/bluntparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sintparrot',
    kind: 'gif',
    name: "Sinterklaas",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sintparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sintparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-pirateparrot',
    kind: 'gif',
    name: "Pirate",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/pirateparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/pirateparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-ceilingparrot',
    kind: 'gif',
    name: "Ceiling",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/ceilingparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/ceilingparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-mardigrasparrot',
    kind: 'gif',
    name: "Mardi Gras",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/mardigrasparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/mardigrasparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-hardhatparrot',
    kind: 'gif',
    name: "Hard Hat",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/hardhatparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/hardhatparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-flyingmoneyparrot',
    kind: 'gif',
    name: "Flying Money",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/flyingmoneyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/flyingmoneyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-portalorangeparrot',
    kind: 'gif',
    name: "Portal Parrot (Orange Portal)",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/portalorangeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/portalorangeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-portalblueparrot',
    kind: 'gif',
    name: "Portal Parrot (Blue Portal)",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/portalblueparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/portalblueparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-reverseportalorangeparrot',
    kind: 'gif',
    name: "Reverse Portal Parrot (Orange Portal)",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseportalorangeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseportalorangeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-reverseportalblueparrot',
    kind: 'gif',
    name: "Reverse Portal Parrot (Blue Portal)",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseportalblueparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/reverseportalblueparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-bunnyparrot',
    kind: 'gif',
    name: "Bunny",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/bunnyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/bunnyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-norwegianblueparrot',
    kind: 'gif',
    name: "Norwegian Blue",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/norwegianblueparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/norwegianblueparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-transparront',
    kind: 'gif',
    name: "Transparront",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/transparront.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/transparront.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-brazilianplayerparrot',
    kind: 'gif',
    name: "Brazilian Player",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/brazilianplayerparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/brazilianplayerparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-brazilianfanparrot',
    kind: 'gif',
    name: "Brazilian Fan",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/brazilianfanparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/brazilianfanparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-spyparrot',
    kind: 'gif',
    name: "Spy",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/spyparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/spyparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-marshmallowparrot',
    kind: 'gif',
    name: "Marshmallow",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/marshmallowparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/marshmallowparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-whitewalkerparrot',
    kind: 'gif',
    name: "White Walker",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/whitewalkerparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/whitewalkerparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-calvinist_parrot',
    kind: 'gif',
    name: "Calvinist",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/calvinist_parrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/calvinist_parrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-frenchparrot',
    kind: 'gif',
    name: "French",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/frenchparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/frenchparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-githubparrot',
    kind: 'gif',
    name: "Github Party",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/githubparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/githubparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-bootlegparrot',
    kind: 'gif',
    name: "Bootleg",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/bootlegparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/bootlegparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-bikerparrot',
    kind: 'gif',
    name: "Biker",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-inverseparrot',
    kind: 'gif',
    name: "Inverse",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/inverseparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/inverseparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-pingpongparrot',
    kind: 'gif',
    name: "Ping Pong",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/pingpongparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/pingpongparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-laptop_parrot',
    kind: 'gif',
    name: "Laptop",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/laptop_parrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/laptop_parrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-60fpsparrot',
    kind: 'gif',
    name: "60fps",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/60fpsparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/60fpsparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-redhatparrot',
    kind: 'gif',
    name: "Red Hat",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/redhatparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/redhatparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-footballparrot',
    kind: 'gif',
    name: "Football",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/footballparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/footballparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-flowerparrot',
    kind: 'gif',
    name: "Flower",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/flowerparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/flowerparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-parrotnotfound',
    kind: 'gif',
    name: "Parrot Not Found",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/parrotnotfound.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/parrotnotfound.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-spinningparrot',
    kind: 'gif',
    name: "Spinning",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/spinningparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/spinningparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-redenvelopeparrot',
    kind: 'gif',
    name: "Red Envelope",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/redenvelopeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/redenvelopeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-grouchoparrot',
    kind: 'gif',
    name: "Groucho",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/grouchoparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/grouchoparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-chicoparrot',
    kind: 'gif',
    name: "Chico",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/chicoparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/chicoparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-harpoparrot',
    kind: 'gif',
    name: "Harpo",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/harpoparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/harpoparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-vikingparrot',
    kind: 'gif',
    name: "Viking",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/vikingparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/vikingparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-darkmodeparrot',
    kind: 'gif',
    name: "Dark Mode",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/darkmodeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/darkmodeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-tiedyeparrot',
    kind: 'gif',
    name: "Tie Dye",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/tiedyeparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/tiedyeparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-horizontalparrot',
    kind: 'gif',
    name: "Horizontal",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/horizontalparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/horizontalparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-sherlockholmesparrot',
    kind: 'gif',
    name: "Sherlock",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/sherlockholmesparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/sherlockholmesparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-tennisparrot',
    kind: 'gif',
    name: "Tennis",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/tennisparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/tennisparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-originalparrot',
    kind: 'gif',
    name: "Original",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/originalparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/originalparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-bobaparrot',
    kind: 'gif',
    name: "Boba",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/bobaparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/bobaparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-backwardsparrot',
    kind: 'gif',
    name: "Backwards",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/backwardsparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/backwardsparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-ripparrot',
    kind: 'gif',
    name: "RIP",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/ripparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/ripparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-shortparrot',
    kind: 'gif',
    name: "Short",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/shortparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/shortparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-braveheartparrot',
    kind: 'gif',
    name: "Braveheart",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/braveheartparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/braveheartparrot.gif',
    createdAt: CREATED,
  },
  {
    id: 'builtin-gif-exceptionallyfastparrot',
    kind: 'gif',
    name: "Exceptionally Fast",
    previewUrl: 'https://cultofthepartyparrot.com/parrots/hd/exceptionallyfastparrot.gif',
    assetUrl: 'https://cultofthepartyparrot.com/parrots/hd/exceptionallyfastparrot.gif',
    createdAt: CREATED,
  },
];
